### ISSUE TITLE
skipping some redos with/without vundo?

### ISSUE THREAD

**Issue by Inc0n** [casouri/vundo#53]
I was using vundo today to unravel a mystery of an edit that happened somehow, and it helped me identify which edit had the problem.

Now I have even a tricker part would like to solve: redo all the rest of the edits, but this problematic one.

Would this be a possibility with vundo? I feel like this could be an interesting idea.

Me myself is thinking, it may be an better idea to create a new undo branch, and not directly changing the undo history, and I also do not know how to make that happen yet. Would appreciate for all advises.

Lastly, I would most certainly apreciate some feedback some this idea also! 
Thanks!

**Comment by ideasman42** [comment]
(not the author of vundo here), this seems outside the scope of vundo, requiring large changes for a special case which is likely to be error prone, since the edit removed from undo history may be part of future editing operations.

Typically in these cases I undo... copy the good state, redo then paste it into the latest buffer. It's a bit awkward but I'm not sure alternatives are better.

**Comment by Inc0n** [comment]
Thanks for the insights! I am going to close this for relevancy and have posted on reddit instead, perhaps someone would provide an interesting solution for this problem, or to spark some other people to come up with any solutions if any at all.
